import {execFile} from 'node:child_process'; import {promisify} from 'node:util'; import {readFile,writeFile,mkdir} from 'node:fs/promises'; import path from 'node:path'; import {parse} from 'yaml'; import type {Task,Policy,Evidence,CommandResult,Criterion,Status} from './types.js';
const exec=promisify(execFile);
export async function loadYaml<T>(file:string):Promise<T>{return parse(await readFile(file,'utf8')) as T}
export function validateTask(t:Task):void{if(!t?.task?.title||!Array.isArray(t.task.acceptanceCriteria)||!t.workspace?.path)throw Error('invalid task schema')}
export function validatePolicy(p:Policy):void{if(!p||!Array.isArray(p.commands))throw Error('invalid policy schema'); for(const c of p.commands){if(!c.name||!Array.isArray(c.argv)||!c.argv.length)throw Error('invalid command schema')}}
function unsafe(a:string[]){return a.some(x=>/[;&|`$<>\\]|\.\.(?:[\\/]|$)/.test(x))}
export async function runCommand(name:string,argv:string[],policy:Policy):Promise<CommandResult>{const p=policy.commands?.find(c=>c.name===name); if(!p||JSON.stringify(p.argv)!==JSON.stringify(argv)||unsafe(argv))return {name,argv,status:'blocked',reason:'not allowlisted or unsafe'}; const start=Date.now(); try{const r=await exec(argv[0],argv.slice(1),{shell:false,timeout:p.timeoutMs??30000,maxBuffer:p.maxOutput??100000}); return {name,argv,status:'passed',stdout:r.stdout.slice(0,p.maxOutput??100000),stderr:r.stderr.slice(0,p.maxOutput??100000),exitCode:0,durationMs:Date.now()-start}}catch(e){const x=e as {code?:number;stdout?:string;stderr?:string;killed?:boolean}; return {name,argv,status:x.killed?'blocked':'failed',stdout:x.stdout?.slice(0,p.maxOutput??100000),stderr:x.stderr?.slice(0,p.maxOutput??100000),exitCode:x.code,reason:x.killed?'timeout':'non-zero exit',durationMs:Date.now()-start}}}
export async function gitScope(repo:string):Promise<{files:string[];dependencyChanges:string[];assessment:'in-scope'|'review-needed'|'out-of-scope'}>{const r=await exec('git',['status','--short'],{cwd:repo,shell:false}); const files=r.stdout.split('\n').filter(Boolean).map(x=>x.slice(3).trim()); const deps=files.filter(x=>/package(-lock)?\.json|yarn\.lock|pnpm-lock\.yaml|requirements\.txt|Cargo\.lock/.test(x)); return {files,dependencyChanges:deps,assessment:deps.length?'review-needed':'in-scope'}}
export function overall(v:CommandResult[],criteria:Criterion[],scope:Evidence['scope']):Status{if(v.some(x=>x.status==='blocked')||scope.assessment==='out-of-scope')return 'blocked'; if(v.some(x=>x.status==='failed'))return 'failed'; if(v.some(x=>x.status==='skipped'||x.status==='blocked')||criteria.some(x=>x.status==='unverified'||x.status==='failed')||scope.assessment==='review-needed')return 'needs-review'; return 'passed'}
export async function verify(taskFile:string,policyFile:string,outDir:string):Promise<Evidence>{const t=await loadYaml<Task>(taskFile); const p=await loadYaml<Policy>(policyFile); validateTask(t);validatePolicy(p); const criteria=t.task.acceptanceCriteria.map((x,i)=>typeof x==='string'?{id:`AC-${i+1}`,text:x,status:'unverified' as const}:{...x,status:x.status??'unverified'}); const validation:CommandResult[]=[]; for(const n of p.requiredCommands??[]) {const c=p.commands?.find(x=>x.name===n); validation.push(c?await runCommand(n,c.argv,p):{name:n,argv:[],status:'skipped',reason:'missing policy command'})} const scope=await gitScope(t.workspace.path); const e:Evidence={schemaVersion:'0.1',runId:t.run?.id??`run-${Date.now()}`,timestamp:new Date().toISOString(),adapter:t.run?.adapter??'generic',status:overall(validation,criteria,scope),task:{title:t.task.title,criteria},validation,scope,risks:scope.dependencyChanges.length?['dependency change requires review']:[],gaps:criteria.filter(x=>x.status==='unverified').map(x=>x.id),artifacts:[],improvements:[]}; await mkdir(outDir,{recursive:true}); await writeFile(path.join(outDir,'evidence.json'),JSON.stringify(e,null,2)+'\n'); await writeFile(path.join(outDir,'proofline-report.md'),report(e)); return e}
export function report(e:Evidence):string{return `# Proofline report\n\n**Status: ${e.status.toUpperCase()}**\n\n## Acceptance criteria\n${e.task.criteria.map(c=>`- ${c.status==='passed'?'✓':'?'} ${c.id}: ${c.text}`).join('\n')}\n\n## Validation\n${e.validation.map(v=>`- ${v.status}: ${v.name}${v.reason?` — ${v.reason}`:''}`).join('\n')}\n\n## Scope\n- ${e.scope.assessment}: ${e.scope.files.length} changed files\n- Dependencies: ${e.scope.dependencyChanges.join(', ')||'none'}\n\n## Gaps\n${e.gaps.map(x=>`- ${x}`).join('\n')||'- none'}\n`}
